[package]
name = "RayzGui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = { version = "0.28.1", features = ["all_loaders"] }
env_logger = "0.11.3"
image = "0.25.1"
